language: nix
env:
  - NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz"

script:
   # Test all default.nix
   - find . -name default.nix -exec nix-instantiate {} 2>/dev/null \;
   # Test the NixOS config
   - nix-instantiate nixos/fake.nix
